runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /go-lanscan
  static_files: go-lanscan
  upload: go-lanscan

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

